version: '3'

services:
  desenv-web-pg:
    image: bitnami/postgresql
    ports:
      - 50432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=web-nodejs